# Generated by Django 4.1.7 on 2023-03-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_registration', '0002_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
