# Generated by Django 4.1.7 on 2023-03-23 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_new_age_new_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EductionLevel', models.CharField(blank=True, choices=[('High School Graduate', 'High School Graduate'), ('Some College', 'Some College'), ('Associate Degree', 'Associate Degree'), ('Bachelor Degree', 'Bachelor Degree'), ('MBA, Masters', 'MBA, Masters'), ('Doctorate', 'Doctorate')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HealthStatus', models.CharField(blank=True, choices=[('Healthy', 'Healthy'), ('Unhealthy', 'Unhealthy')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseHoldProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HouseHoldProgram', models.CharField(choices=[('Public Work', 'Public work'), ('Direct Support', 'Direct Support')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MartialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MartialStatus', models.CharField(blank=True, choices=[('Single', 'Single'), ('In a Relationship', 'In a Relationship'), ('Engaged', 'Engaged'), ('Married', 'Married'), ('Widowed', 'Widowed')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedDate', models.DateTimeField(auto_created=True, null=True)),
                ('UpdatedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('Status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, null=True)),
                ('HouseholdMemberIdNumber', models.CharField(max_length=64, null=True)),
                ('NationalMemberIdNumber', models.CharField(max_length=64, null=True)),
                ('FirstName', models.CharField(max_length=64, null=True)),
                ('FatherName', models.CharField(max_length=64, null=True)),
                ('GrandFatherName', models.CharField(max_length=64, null=True)),
                ('MotherFullName', models.CharField(max_length=64, null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('DateOfBirth', models.DateTimeField(null=True)),
                ('Age', models.IntegerField(null=True)),
                ('RegistrationDate', models.DateTimeField(null=True)),
                ('CreatedBy', models.CharField(max_length=64, null=True, verbose_name=models.CharField(max_length=64, null=True))),
                ('UpdatedBy', models.CharField(max_length=64, null=True, verbose_name=models.CharField(max_length=64, null=True))),
                ('Educationlevel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.educationlevel')),
                ('Healthstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.healthstatus')),
                ('Martialstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.martialstatus')),
            ],
        ),
        migrations.DeleteModel(
            name='New',
        ),
        migrations.RemoveField(
            model_name='household',
            name='Name',
        ),
        migrations.AddField(
            model_name='household',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='FemaleMemberSize',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='HouseHoldIdNumber',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='MaleMemberSize',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='NumberOfFemaleAbleBody',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='NumberOfMaleAbleBody',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='NumberOfParticipatingFemale',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='NumberOfParticipatingMale',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='RegistrationDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='UpdatedDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='RelationToHousehold',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.household'),
        ),
        migrations.AddField(
            model_name='household',
            name='HouseholdProgram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.householdprogram'),
        ),
    ]
