# Generated by Django 4.1.7 on 2023-03-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_educationlevel_healthstatus_householdprogram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Age',
        ),
        migrations.AlterField(
            model_name='member',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='DateOfBirth',
            field=models.DateField(null=True),
        ),
    ]
