# Generated by Django 4.1.7 on 2023-03-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_member_age_alter_member_createddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='TodayDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='RegistrationDate',
            field=models.DateField(null=True),
        ),
    ]
