# Generated by Django 4.1.7 on 2023-03-23 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_household_updateddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BeneficiaryType', models.CharField(blank=True, choices=[('Primary Beneficiary', 'Primary Beneficiary'), ('Contingent Beneficiary', 'Contingent Beneficiary'), ('Residuary Beneficiary', 'Resiudary Beneficiary')], max_length=64, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='Educationlevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.educationlevel'),
        ),
        migrations.AlterField(
            model_name='member',
            name='Healthstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.healthstatus'),
        ),
        migrations.AlterField(
            model_name='member',
            name='RegistrationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='RelationToHousehold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.household'),
        ),
        migrations.AddField(
            model_name='member',
            name='Beneficiarytype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.beneficiarytype'),
        ),
    ]
