# Generated by Django 4.1.7 on 2023-03-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_member_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='DateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
