# Generated by Django 4.1.7 on 2023-03-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_remove_member_age_alter_member_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='FemaleMemberSize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='HouseHoldIdNumber',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='HouseholdProgram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.householdprogram'),
        ),
        migrations.AlterField(
            model_name='household',
            name='MaleMemberSize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='NumberOfFemaleAbleBody',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='NumberOfMaleAbleBody',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='NumberOfParticipatingFemale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='NumberOfParticipatingMale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='RegistrationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='Status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='householdprogram',
            name='HouseHoldProgram',
            field=models.CharField(blank=True, choices=[('Public Work', 'Public work'), ('Direct Support', 'Direct Support')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='CreatedBy',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='FatherName',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='FirstName',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='GrandFatherName',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='HouseholdMemberIdNumber',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='Martialstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.martialstatus'),
        ),
        migrations.AlterField(
            model_name='member',
            name='MotherFullName',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='NationalMemberIdNumber',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='Status',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='UpdatedBy',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
