# Generated by Django 4.1.7 on 2023-03-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_alter_member_updateddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='TodayDate',
        ),
    ]
