# Generated by Django 4.1.7 on 2023-03-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_remove_member_todaydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='CreatedBy',
        ),
    ]
