# Generated by Django 4.1.7 on 2023-03-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_remove_member_updatedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='UpdatedDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
