# Generated by Django 4.1.7 on 2023-04-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_alter_household_registrationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdprogram',
            name='HouseHoldProgram',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
